# -------------------------------------------------------------------------------
# Configuration file for http://travis-ci.org/#!/elasticsearch/elasticsearch-ruby
# -------------------------------------------------------------------------------

language: ruby

branches:
  only:
    - '0.4'
    - travis

rvm:
  - 1.8.7
  - 1.9.3
  - 2.1.0

jdk:
  - openjdk7

env:
  - TEST_SUITE=unit
  - TEST_SUITE=integration

before_install:
  - gem update --system
  - gem --version

install:
  - test $TEST_SUITE == 'integration' && curl -# https://download.elasticsearch.org/elasticsearch/elasticsearch/elasticsearch-0.90.10.tar.gz | tar xz -C /tmp || true

before_script:
  - git submodule update --init --recursive || true
  - rake elasticsearch:update
  - rake bundle:clean
  - rake bundle:install

script:
  - SERVER=start TEST_BUILD_REF=origin/0.90 TEST_CLUSTER_COMMAND=/tmp/elasticsearch-0.90.10/bin/elasticsearch bundle exec rake test:$TEST_SUITE

matrix:
  exclude:
    - rvm: 1.8.7
      jdk: openjdk7
      env: TEST_SUITE=integration

notifications:
  disable: true
