name: Ruby
on:
  push:
    branches:
      - master
      - 7.x
      - 6.x
  pull_request:
    branches:
      - master
      - 7.x
      - 6.x
jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        ruby: [ 2.4, 2.5, 2.6, 2.7, jruby ]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
    - name: Build and test with Rake
      run: |
        sudo apt-get install libcurl4-openssl-dev
        ruby -v
        rake bundle:clean
        rake bundle:install
        rake test:unit
